=== leonlinsx/lin-lib/.astro/collections/blog.schema.json
{
  "$ref": "#/definitions/blog",
  "definitions": {
    "blog": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "pubDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "integer",
              "format": "unix-time"
            }
          ]
        },
        "updatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "integer",
              "format": "unix-time"
            }
          ]
        },
        "category": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "featured": {
          "type": "boolean"
        },
        "heroImage": {
          "type": "string"
        },
        "readingTime": {
          "type": "number"
        },
        "slug": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "pubDate"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== leonlinsx/lin-lib/dist/api/search-index.json
[{"slug":"2021_04_10_algo","title":"Book Review: Algorithms to live by","description":"How can we apply algorithms to improve decision making in real life?","category":"Book Review","tags":["behaviour","tech"],"pubDate":"2021-04-10T00:00:00.000Z","heroImage":"/_astro/a_3.CRDTJh8S.webp"},{"slug":"2021_04_17_community","title":"Community as a Concept","description":"CAC to lower your CAC","category":"Tech","tags":["community"],"pubDate":"2021-04-17T00:00:00.000Z","heroImage":"/_astro/c_1.BWSIR5uN.webp"},{"slug":"2021_05_02_art_history","title":"What is art","description":"Different definitions of art over history","category":"Lifestyle","tags":["art"],"pubDate":"2021-05-02T00:00:00.000Z","heroImage":"/_astro/a_1.7FGSv2vE.webp"}]
